services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'application'
      MYSQL_PASSWORD: 'application123'
      MYSQL_DATABASE: 'flask-crud'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - /workspaces/mysql:/var/lib/mysql